### ISSUE TITLE
Сериализатор

### ISSUE THREAD

**Issue by CatWithAutism** [QIWI-API/bill-payments-dotnet-sdk#14]
Пофиксите пожалуйста ваш чудесный сериализатор. Дефолтный, при какой-то там дате или числе, так и не разобрался, выкидывает BillPaymentsServiceException.
![image](https://user-images.githubusercontent.com/28768640/64055101-2d2bff80-cb93-11e9-9a25-a22441d15497.png)
![image](https://user-images.githubusercontent.com/28768640/64055149-767c4f00-cb93-11e9-9099-2f44a60e9245.png)

**Comment by Jamaska** [comment]
Добрый день!
Можете , пожалуйста,  прислать примеры json-ответов при которых возникает ошибка?

**Comment by CatWithAutism** [comment]
К вам уже когда-то обращался человек: https://github.com/QIWI-API/bill-payments-dotnet-sdk/issues/10
Я всего лишь уточнил его слова.
Вы можете это и сами сделать, ибо в среднем, каждый седьмой запрос отлетает с ошибкой на сериализации

**Comment by VladislavLeontev** [comment]
Если при создании клиента использовать Qiwi.BillPayments.Json.Newtonsoft.NewtonsoftMapper, то работает всё из коробки, без дополнительных настроек формата даты.
Но нужно дополнительно установить Qiwi.BillPayments.Json.Newtons пакет из nuget.

**Comment by CatWithAutism** [comment]
Вопрос решается пакетом выше
