### ISSUE TITLE
One or more errors occurred

### ISSUE THREAD

**Issue by Durfald** [QIWI-API/bill-payments-dotnet-sdk#21]
Подскажите, в чем может быть проблема?
One or more errors occurred. (Exception of type 'Qiwi.BillPayments.Exception.BillPaymentsServiceException' was thrown.)
когда проходит оплата вылетает ошибка я не знаю почему.

**Comment by asiryan** [comment]
Тоже самое

**Comment by DarkLexFirst** [comment]
Возникает из за необработанной ошибки десериализации 
Подробнее тут https://github.com/QIWI-API/bill-payments-dotnet-sdk/issues/10

Используйте другой маппер, говорят помогает https://github.com/QIWI-API/bill-payments-dotnet-sdk/issues/14

**Comment by DarkLexFirst** [comment]
возможно это тоже поможет https://github.com/QIWI-API/bill-payments-dotnet-sdk/issues/14

**Comment by Durfald** [comment]
всем спасибо за помощь.
