### ISSUE TITLE
Отсутствует документация в Nuget-пакете

### ISSUE THREAD

**Issue by Fitch24** [QIWI-API/bill-payments-dotnet-sdk#5]
Добрый день.
При установке SDK через Nuget полностью отсутствует какая-либо документация:
![1](https://user-images.githubusercontent.com/42736888/54880878-7f4a5580-4e7c-11e9-87f2-bb60ae618aa2.PNG)
(MS VS Community 15.9.9)

Приходится "подглядывать" документацию в исходниках из браузера, либо собирать SDK из исходников...

**Comment by Jamaska** [comment]
Спасибо за информацию, постараемся в ближайшее время исправить

**Comment by Jamaska** [comment]
Внесли изменения.
