### ISSUE TITLE
Планируется ли добавление асинхронных методов?

### ISSUE THREAD

**Issue by Fitch24** [QIWI-API/bill-payments-dotnet-sdk#6]
Добрый день.
Если я правильно понял, все запросы к API QIWI-Кассы в данный момент выполняются синхронно. Планируется ли добавление в SDK асинхронных версий этих методов, например, _CreateBillAsync_?

**Comment by Jamaska** [comment]
Добрый день !
На сколько критична необходимость данных методов ? Для каких целей вы планируете их использовать ?

**Comment by Fitch24** [comment]
> Для каких целей вы планируете их использовать ?

Для более эффективного распределения ресурсов сервера? SDK выполняет все HTTP-запросы к QIWI-API синхронно. Например, если в контроллере ASP.NET/ASP.NET Core мы используем такой код:
`var bill = client.CreateBill(info);`
то выполнение HTTP-запроса к API ложится на вызывающий поток, т.е. на один из потоков для обработки запросов к серверу ASP.NET. Но если бы SDK мог отправлять HTTP-запросы к API асинхронно и для этого были бы соответствующие методы, например:
`var bill = await client.CreateBillAsync(info);`
то это освобождало бы вызывающий поток на время операции и он мог бы обрабатывать другие входящие запросы, поступающие серверу, что, теоретически, повысило бы максимальное количество одновременно обрабатываемых запросов сервером (запросов в секунду).
Или я ошибаюсь, и гугл меня надурил ([1](https://stackoverflow.com/questions/52942854/webapi-async-vs-sync), [2](https://stackoverflow.com/questions/48015096/not-much-difference-between-asp-net-core-sync-and-async-controller-actions))?

> На сколько критична необходимость данных методов ?

Затрудняюсь ответить, но однозначно предпочел бы использовать асинхронные методы (если бы они были), вместо синхронных. Собственно из-за этого и отказался от использования SDK, реализовав запросы к API собственным кодом (еще меня смутило, что SDK добавляет свои customFields к счетам, но это не критично).

**Comment by Jamaska** [comment]
Рассматриваем возможность доработки, спасибо.

**Comment by Jamaska** [comment]
@Fitch24 , доработали sdk , теперь есть асинхронные методы.
